"""forced company names to be unique

Revision ID: 3573b02d5969
Revises: b050b699e2e0
Create Date: 2019-11-17 20:24:17.444451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3573b02d5969'
down_revision = 'b050b699e2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_company_name', table_name='company')
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.create_index('ix_company_company_name', 'company', ['company_name'], unique=False)
    # ### end Alembic commands ###
