"""added a tag field to Document

Revision ID: 607f00c9b38a
Revises: aced1c5a7d0e
Create Date: 2019-11-30 15:27:56.572916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607f00c9b38a'
down_revision = 'aced1c5a7d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('tag', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_document_company'), 'document', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_company'), table_name='document')
    op.drop_column('document', 'tag')
    # ### end Alembic commands ###
