"""added file location field to documents

Revision ID: aced1c5a7d0e
Revises: 79f89922cdcd
Create Date: 2019-11-30 12:30:41.564556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aced1c5a7d0e'
down_revision = '79f89922cdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_location', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_location')
    # ### end Alembic commands ###
